

// AUTOGENERATED FILE

#include "renderer.h"

#include <stdio.h>
#include "renderer_gl_loader.h"

#ifdef _WIN32
    #include <windows.h>

    #define LOAD(name) \
                do { \
                    name = (name##_t)wglGetProcAddress(#name); \
                    if (!name) { printf("failed to load %s!\n", #name); return } \
                } while (0)
#else
    #include <EGL/egl.h>
    #include <GL/glx.h>

    #define LOAD(name) \
                do { \
                    if (cc_renderer_use_wayland) name = (name##_t)eglGetProcAddress(#name); \
                    else name = (name##_t)glXGetProcAddress((const GLubyte*)name); \
                    if (!name) { printf("failed to load %s!\n", #name); return; } \
                } while(0)
#endif

#define FUNC_C(name, ret_type, ...) \
    name##_t name = NULL


FUNC_C(glCreateShader, GLuint, GLenum type);
FUNC_C(glShaderSource, void, GLuint shader, GLsizei count, const GLchar* const* string, const GLint* length);
FUNC_C(glCompileShader, void, GLuint shader);
FUNC_C(glGetShaderiv, void, GLuint shader, GLenum pname, GLint* params);
FUNC_C(glGetShaderInfoLog, void, GLuint shader, GLsizei bufSize, GLsizei* length, GLchar* infolog);
FUNC_C(glDeleteShader, void, GLuint shader);

FUNC_C(glCreateProgram, GLuint, void);
FUNC_C(glAttachShader, void, GLuint program, GLuint shader);
FUNC_C(glLinkProgram, void, GLuint program);
FUNC_C(glGetProgramiv, void, GLuint program, GLenum pname, GLint* params);
FUNC_C(glGetProgramInfoLog, void, GLuint program, GLsizei bufSize, GLsizei* length, GLchar* infoLog);
FUNC_C(glDeleteProgram, void, GLuint program);

FUNC_C(glGenVertexArrays, void, GLsizei n, GLuint* arrays);
FUNC_C(glGetUniformLocation, GLint, GLuint program, const GLchar* name);
FUNC_C(glGenBuffers, void, GLsizei n, GLuint* buffers);
FUNC_C(glBindBuffer, void, GLenum target, GLuint buffer);
FUNC_C(glBufferData, void, GLenum target, GLsizeiptr size, const void* data, GLenum usage);
FUNC_C(glTexBuffer, void, GLenum target, GLenum internalformat, GLuint buffer);

FUNC_C(glDeleteVertexArrays, void, GLsizei n, const GLuint* arrays);
FUNC_C(glDeleteBuffers, void, GLsizei n, const GLuint* buffers);

FUNC_C(glUseProgram, void, GLuint program);
FUNC_C(glBindVertexArray, void, GLuint array);
FUNC_C(glUniformMatrix4fv, void, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
FUNC_C(glBufferSubData, void, GLenum target, GLintptr offset, GLsizeiptr size, const void* data);
FUNC_C(glUniform1i, void, GLint location, GLint v0);
FUNC_C(glUniform1f, void, GLint location, GLfloat v0);
FUNC_C(glDrawArraysInstanced, void, GLenum mode, GLint first, GLsizei count, GLsizei instancecount);

void cc_gl_load(void) {

LOAD(glCreateShader);
LOAD(glShaderSource);
LOAD(glCompileShader);
LOAD(glGetShaderiv);
LOAD(glGetShaderInfoLog);
LOAD(glDeleteShader);

LOAD(glCreateProgram);
LOAD(glAttachShader);
LOAD(glLinkProgram);
LOAD(glGetProgramiv);
LOAD(glGetProgramInfoLog);
LOAD(glDeleteProgram);

LOAD(glGenVertexArrays);
LOAD(glGetUniformLocation);
LOAD(glGenBuffers);
LOAD(glBindBuffer);
LOAD(glBufferData);
LOAD(glTexBuffer);

LOAD(glDeleteVertexArrays);
LOAD(glDeleteBuffers);

LOAD(glUseProgram);
LOAD(glBindVertexArray);
LOAD(glUniformMatrix4fv);
LOAD(glBufferSubData);
LOAD(glUniform1i);
LOAD(glUniform1f);
LOAD(glDrawArraysInstanced);
}
