# fuck yeah its bash
# you got a problem with that?

echo "

// AUTOGENERATED FILE

#ifndef CC_RENDERER_GL_LOADER_H
#define CC_RENDERER_GL_LOADER_H

#include <GL/gl.h>
#include <stdlib.h>

#define FUNC(name, ret_type, ...) \\
    typedef ret_type (APIENTRYP name##_t)(__VA_ARGS__); \\
    extern name##_t name

" > core/renderer/renderer_gl_loader.h

sed -E 's/^(.*\S.*)$/FUNC(\1);/' core/renderer/renderer_gl_funcs.CCFFT >> core/renderer/renderer_gl_loader.h

echo "
#endif" >> core/renderer/renderer_gl_loader.h


echo "

// AUTOGENERATED FILE

#include \"renderer.h\"

#include <stdio.h>
#include \"renderer_gl_loader.h\"

#ifdef _WIN32
    #include <windows.h>

    #define LOAD(name) \\
                do { \\
                    name = (name##_t)wglGetProcAddress(#name); \\
                    if (!name) { printf(\"failed to load %s!\n\", #name); return } \\
                } while (0)
#else
    #include <EGL/egl.h>
    #include <GL/glx.h>

    #define LOAD(name) \\
                do { \\
                    if (cc_renderer_use_wayland) name = (name##_t)eglGetProcAddress(#name); \\
                    else name = (name##_t)glXGetProcAddress((const GLubyte*)name); \\
                    if (!name) { printf(\"failed to load %s!\n\", #name); return; } \\
                } while(0)
#endif

#define FUNC_C(name, ret_type, ...) \\
    name##_t name = NULL

" > core/renderer/renderer_gl_loader.c

sed -E 's/^(.*\S.*)$/FUNC_C(\1);/' core/renderer/renderer_gl_funcs.CCFFT >> core/renderer/renderer_gl_loader.c

echo "
void cc_gl_load(void) {
" >> core/renderer/renderer_gl_loader.c

sed -E 's/^([^,]+),.*$/LOAD(\1);/' core/renderer/renderer_gl_funcs.CCFFT >> core/renderer/renderer_gl_loader.c

echo "}" >> core/renderer/renderer_gl_loader.c
